---
image: 
  - Visual Studio 2017
  - Visual Studio 2019
build: false
version: '{build}'

platform: x64

notifications:
  - provider: Email
    to:
      - jesse.tov@gmail.com
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: false

environment:
  matrix:
    - target: x86_64-pc-windows-msvc
      channel: 1.32.0
    - target: x86_64-pc-windows-gnu
      channel: 1.32.0
    - target: x86_64-pc-windows-msvc
      channel: stable
    - target: x86_64-pc-windows-gnu
      channel: stable
    - target: x86_64-pc-windows-msvc
      channel: beta
    - target: x86_64-pc-windows-gnu
      channel: beta
    - target: x86_64-pc-windows-msvc
      channel: nightly
    - target: x86_64-pc-windows-gnu
      channel: nightly

matrix:
  allow_failures:
    - target: x86_64-pc-windows-msvc
      channel: nightly
    - target: x86_64-pc-windows-gnu
      channel: nightly
    #  This one shouldn't fail, but I don't know why it's failing yet:
    - target: x86_64-pc-windows-gnu
      channel: beta

install:
  - curl -sSf -o rustup-init.exe https://win.rustup.rs
  - rustup-init.exe --default-host %target% --default-toolchain %channel% -y
  - set PATH=C:\Users\appveyor\.cargo\bin;%PATH%
  - rustc -Vv
  - cargo -V
  - cd %APPVEYOR_BUILD_FOLDER%
  - git submodule update --init --recursive

test_script:
  - cargo build --verbose
  - cargo test

for:
  - matrix:
      only:
        - target: x86_64-pc-windows-gnu
    install:
      - curl -sSf -o rustup-init.exe https://win.rustup.rs
      - rustup-init.exe --default-host %target% --default-toolchain %channel% -y
      - set PATH=C:\msys64\usr\bin;C:\Users\appveyor\.cargo\bin;%PATH%
      - bash -lc "pacman --noconfirm -S automake autoconf mingw-w64-x86_64-clang libtool"
      - rustc -Vv
      - cargo -V
      - cd %APPVEYOR_BUILD_FOLDER%
      - git submodule update --init --recursive
    test_script:
      - env MSYSTEM=MINGW64 bash -lc 'cd $APPVEYOR_BUILD_FOLDER; cargo build --verbose'
      - env MSYSTEM=MINGW64 bash -lc 'cd $APPVEYOR_BUILD_FOLDER; cargo test'

cache:
  - C:\Users\appveyor\.cargo
  - compiler\vendor
